package com.sf.leasing.lead.infrastructure.locking;

import com.sf.leasing.lead.domain.exception.BusinessException;
import com.sf.leasing.lead.domain.exception.ErrorCodes;
import io.quarkus.redis.datasource.RedisDataSource;
import io.quarkus.redis.datasource.string.StringCommands;
import io.quarkus.redis.datasource.keys.KeyCommands;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import jakarta.persistence.EntityManager;
import org.jboss.logging.Logger;

import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

/**
 * Generates lock-protected sequential IDs.
 *
 * Rule LP2.3: LRN generated by atomically locking a central control record,
 * incrementing, then releasing. Lock timeout of 15 seconds returns error D283.
 */
@ApplicationScoped
public class RedisSequenceGenerator {

    private static final Logger LOG = Logger.getLogger(RedisSequenceGenerator.class);
    private static final long LOCK_TTL_SECONDS = 15L;
    private static final int MAX_WAIT_MS = 14_000;
    private static final int POLL_INTERVAL_MS = 100;

    @Inject
    RedisDataSource redisDataSource;

    @Inject
    EntityManager em;

    /**
     * Generates LRN in format: LS-YYYYMM-NNNNNN.
     * Resets monthly; rolls back to 000001 on new month/year.
     */
    public String generateLrn(String lobPrefix) {
        LocalDate today = LocalDate.now();
        String sequenceName = "LRN_" + lobPrefix;
        String yearMonth = today.format(DateTimeFormatter.ofPattern("yyyyMM"));

        long seq = nextSequence(sequenceName, true, today.getYear(), today.getMonthValue());
        return String.format("%s-%s-%06d", lobPrefix, yearMonth, seq);
    }

    /**
     * Generates Temp Customer Number in format: TMP-YYYY-NNNNNN.
     * Resets annually per system parameter.
     */
    public String generateTempCustomerNumber() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("TEMP_CUSTOMER", false, today.getYear(), null);
        return String.format("TMP-%s-%06d", year, seq);
    }

    /**
     * Generates Prospect Business ID in format: PR-YYYY-NNNNNN.
     * Resets annually. Called only after successful KYC validation (PP3.1).
     */
    public String generateProspectId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("PROSPECT_ID", false, today.getYear(), null);
        return String.format("PR-%s-%06d", year, seq);
    }

    /**
     * Generates Meeting ID in format: MTG-YYYY-NNNNN.
     * Resets annually. Always generates a new ID — amendment creates a new record.
     */
    public String generateMeetingId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("MEETING_ID", false, today.getYear(), null);
        return String.format("MTG-%s-%05d", year, seq);
    }

    /**
     * Generates Opportunity ID in format: OPP-YYYY-NNNNNN.
     * Resets annually. Generated on Opportunity creation (PP5).
     */
    public String generateOpportunityId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("OPPORTUNITY_ID", false, today.getYear(), null);
        return String.format("OPP-%s-%06d", year, seq);
    }

    /**
     * Generates Quote ID in format: QT-YYYY-NNNNNN.
     * Resets annually. Each version of a quote gets its own ID (PP6).
     */
    public String generateQuoteId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("QUOTE_ID", false, today.getYear(), null);
        return String.format("QT-%s-%06d", year, seq);
    }

    /**
     * Generates Application ID in format: APP-YYYY-NNNNNN.
     * Resets annually. Generated on Application initiation (PP7.1).
     */
    public String generateApplicationId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("APPLICATION_ID", false, today.getYear(), null);
        return String.format("APP-%s-%06d", year, seq);
    }

    /**
     * Generates Enterprise Customer ID in format: CUST-YYYY-NNNNNN.
     * Resets annually. Generated only after KYC = Complete AND CAM = Approved (PP8.1).
     */
    public String generateCustomerId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("CUSTOMER_ID", false, today.getYear(), null);
        return String.format("CUST-%s-%06d", year, seq);
    }

    private long nextSequence(String sequenceName, boolean monthlyReset, int year, Integer month) {
        String lockKey = "seq_lock:" + sequenceName;
        String lockValue = UUID.randomUUID().toString();

        StringCommands<String, String> strings = redisDataSource.string(String.class);
        KeyCommands<String> keys = redisDataSource.key(String.class);

        // Try to acquire distributed lock using SETNX + EXPIRE (atomically via Lua in prod;
        // for Phase 1: SETNX then EXPIRE is acceptable given sub-millisecond gap)
        long started = System.currentTimeMillis();

        while (true) {
            Boolean acquired = strings.setnx(lockKey, lockValue);
            if (Boolean.TRUE.equals(acquired)) {
                // Set TTL immediately after acquiring
                keys.expire(lockKey, Duration.ofSeconds(LOCK_TTL_SECONDS));
                break;
            }
            long elapsed = System.currentTimeMillis() - started;
            if (elapsed >= MAX_WAIT_MS) {
                throw new BusinessException(
                    ErrorCodes.DOCUMENT_NUMBER_IN_USE,
                    "This Document Number Is Being Used By Another Person."
                );
            }
            try {
                Thread.sleep(POLL_INTERVAL_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new BusinessException(ErrorCodes.DOCUMENT_NUMBER_IN_USE, "Sequence generation interrupted.");
            }
        }

        try {
            return incrementSequenceInDb(sequenceName, monthlyReset, year, month);
        } finally {
            // Release lock only if we still own it (compare-and-delete)
            String current = strings.get(lockKey);
            if (lockValue.equals(current)) {
                keys.del(lockKey);
            }
        }
    }

    @Transactional(Transactional.TxType.REQUIRES_NEW)
    long incrementSequenceInDb(String sequenceName, boolean monthlyReset, int year, Integer month) {
        Object[] row = (Object[]) em.createNativeQuery(
            "SELECT current_value, reset_year, reset_month FROM sequence_control WHERE sequence_name = ?1 FOR UPDATE"
        ).setParameter(1, sequenceName).getSingleResult();

        long currentValue = ((Number) row[0]).longValue();
        int storedYear    = ((Number) row[1]).intValue();
        Integer storedMonth = row[2] != null ? ((Number) row[2]).intValue() : null;

        boolean needsReset = monthlyReset
            ? (storedYear != year || (storedMonth != null && !storedMonth.equals(month)))
            : (storedYear != year);

        long nextValue = needsReset ? 1L : currentValue + 1L;

        em.createNativeQuery(
            "UPDATE sequence_control SET current_value = ?1, reset_year = ?2, reset_month = ?3, updated_at = CURRENT_TIMESTAMP WHERE sequence_name = ?4"
        )
            .setParameter(1, nextValue)
            .setParameter(2, year)
            .setParameter(3, month)
            .setParameter(4, sequenceName)
            .executeUpdate();

        return nextValue;
    }
}
