package com.sf.leasing.lead.infrastructure.locking;

import com.sf.leasing.lead.domain.exception.BusinessException;
import com.sf.leasing.lead.domain.exception.ErrorCodes;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

/**
 * Generates lock-protected sequential IDs.
 *
 * Rule LP2.3: LRN generated by atomically locking a central control record,
 * incrementing, then releasing. Lock timeout of 15 seconds returns error D283.
 */
@Component
public class RedisSequenceGenerator {

    private static final Logger LOG = LoggerFactory.getLogger(RedisSequenceGenerator.class);
    private static final long LOCK_TTL_SECONDS = 15L;
    private static final int MAX_WAIT_MS = 14_000;
    private static final int POLL_INTERVAL_MS = 100;

    private final StringRedisTemplate redisTemplate;

    @PersistenceContext
    private EntityManager em;

    public RedisSequenceGenerator(StringRedisTemplate redisTemplate) {
        this.redisTemplate = redisTemplate;
    }

    public String generateLrn(String lobPrefix) {
        LocalDate today = LocalDate.now();
        String sequenceName = "LRN_" + lobPrefix;
        String yearMonth = today.format(DateTimeFormatter.ofPattern("yyyyMM"));
        long seq = nextSequence(sequenceName, true, today.getYear(), today.getMonthValue());
        return String.format("%s-%s-%06d", lobPrefix, yearMonth, seq);
    }

    public String generateTempCustomerNumber() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("TEMP_CUSTOMER", false, today.getYear(), null);
        return String.format("TMP-%s-%06d", year, seq);
    }

    public String generateProspectId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("PROSPECT_ID", false, today.getYear(), null);
        return String.format("PR-%s-%06d", year, seq);
    }

    public String generateMeetingId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("MEETING_ID", false, today.getYear(), null);
        return String.format("MTG-%s-%05d", year, seq);
    }

    public String generateOpportunityId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("OPPORTUNITY_ID", false, today.getYear(), null);
        return String.format("OPP-%s-%06d", year, seq);
    }

    public String generateQuoteId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("QUOTE_ID", false, today.getYear(), null);
        return String.format("QT-%s-%06d", year, seq);
    }

    public String generateApplicationId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("APPLICATION_ID", false, today.getYear(), null);
        return String.format("APP-%s-%06d", year, seq);
    }

    public String generateCustomerId() {
        LocalDate today = LocalDate.now();
        String year = String.valueOf(today.getYear());
        long seq = nextSequence("CUSTOMER_ID", false, today.getYear(), null);
        return String.format("CUST-%s-%06d", year, seq);
    }

    private long nextSequence(String sequenceName, boolean monthlyReset, int year, Integer month) {
        String lockKey = "seq_lock:" + sequenceName;
        String lockValue = UUID.randomUUID().toString();

        long started = System.currentTimeMillis();
        while (true) {
            Boolean acquired = redisTemplate.opsForValue()
                .setIfAbsent(lockKey, lockValue, Duration.ofSeconds(LOCK_TTL_SECONDS));
            if (Boolean.TRUE.equals(acquired)) {
                break;
            }
            long elapsed = System.currentTimeMillis() - started;
            if (elapsed >= MAX_WAIT_MS) {
                throw new BusinessException(
                    ErrorCodes.DOCUMENT_NUMBER_IN_USE,
                    "This Document Number Is Being Used By Another Person."
                );
            }
            try {
                Thread.sleep(POLL_INTERVAL_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new BusinessException(ErrorCodes.DOCUMENT_NUMBER_IN_USE, "Sequence generation interrupted.");
            }
        }

        try {
            return incrementSequenceInDb(sequenceName, monthlyReset, year, month);
        } finally {
            String current = redisTemplate.opsForValue().get(lockKey);
            if (lockValue.equals(current)) {
                redisTemplate.delete(lockKey);
            }
        }
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public long incrementSequenceInDb(String sequenceName, boolean monthlyReset, int year, Integer month) {
        Object[] row = (Object[]) em.createNativeQuery(
            "SELECT current_value, reset_year, reset_month FROM sequence_control WHERE sequence_name = ?1 FOR UPDATE"
        ).setParameter(1, sequenceName).getSingleResult();

        long currentValue = ((Number) row[0]).longValue();
        int storedYear    = ((Number) row[1]).intValue();
        Integer storedMonth = row[2] != null ? ((Number) row[2]).intValue() : null;

        boolean needsReset = monthlyReset
            ? (storedYear != year || (storedMonth != null && !storedMonth.equals(month)))
            : (storedYear != year);

        long nextValue = needsReset ? 1L : currentValue + 1L;

        em.createNativeQuery(
            "UPDATE sequence_control SET current_value = ?1, reset_year = ?2, reset_month = ?3, updated_at = CURRENT_TIMESTAMP WHERE sequence_name = ?4"
        )
            .setParameter(1, nextValue)
            .setParameter(2, year)
            .setParameter(3, month)
            .setParameter(4, sequenceName)
            .executeUpdate();

        return nextValue;
    }
}
